/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ClinicClinicIdRouteImport } from './routes/clinic.$clinicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicIdRoute = ClinicClinicIdRouteImport.update({
  id: '/clinic/$clinicId',
  path: '/clinic/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/suggest': typeof SuggestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/suggest': typeof SuggestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/suggest': typeof SuggestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/clinic/$clinicId': typeof ClinicClinicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/download'
    | '/suggest'
    | '/dashboard'
    | '/api/suggest'
    | '/clinic/$clinicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/download'
    | '/suggest'
    | '/dashboard'
    | '/api/suggest'
    | '/clinic/$clinicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/download'
    | '/suggest'
    | '/_authenticated/dashboard'
    | '/api/suggest'
    | '/clinic/$clinicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DownloadRoute: typeof DownloadRoute
  SuggestRoute: typeof SuggestRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ClinicClinicIdRoute: typeof ClinicClinicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicId': {
      id: '/clinic/$clinicId'
      path: '/clinic/$clinicId'
      fullPath: '/clinic/$clinicId'
      preLoaderRoute: typeof ClinicClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DownloadRoute: DownloadRoute,
  SuggestRoute: SuggestRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ClinicClinicIdRoute: ClinicClinicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
